deployer:
  name: Jason
package:
  filename: Speedwagon-amd64.msi
  path: \\files.library.illinois.edu\groupfiles\Digital Content Creation\SCCM Upload\
maintainer:
  name: Henry Borchers
  email: hborcher@illinois.edu
deployment:
  hostnames:
    - LIBSTFPRE12
    - LIBSTFDCC06
    - LIBSTFDCC02
